// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_a89-vmBpv_9lSJIHvQoCVelz0-_8Ptg',
    appId: '1:664325323108:web:5578343b0c37fc7d62e271',
    messagingSenderId: '664325323108',
    projectId: 'readora-319f5',
    authDomain: 'readora-319f5.firebaseapp.com',
    storageBucket: 'readora-319f5.firebasestorage.app',
    measurementId: 'G-13RM8JW1HH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_a89-vmBpv_9lSJIHvQoCVelz0-_8Ptg',
    appId: '1:664325323108:android:YOUR_ANDROID_APP_ID',
    messagingSenderId: '664325323108',
    projectId: 'readora-319f5',
    authDomain: 'readora-319f5.firebaseapp.com',
    storageBucket: 'readora-319f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_a89-vmBpv_9lSJIHvQoCVelz0-_8Ptg',
    appId: '1:664325323108:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '664325323108',
    projectId: 'readora-319f5',
    authDomain: 'readora-319f5.firebaseapp.com',
    storageBucket: 'readora-319f5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_a89-vmBpv_9lSJIHvQoCVelz0-_8Ptg',
    appId: '1:664325323108:ios:YOUR_MACOS_APP_ID',
    messagingSenderId: '664325323108',
    projectId: 'readora-319f5',
    authDomain: 'readora-319f5.firebaseapp.com',
    storageBucket: 'readora-319f5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_a89-vmBpv_9lSJIHvQoCVelz0-_8Ptg',
    appId: '1:664325323108:web:5578343b0c37fc7d62e271',
    messagingSenderId: '664325323108',
    projectId: 'readora-319f5',
    authDomain: 'readora-319f5.firebaseapp.com',
    storageBucket: 'readora-319f5.firebasestorage.app',
    measurementId: 'G-13RM8JW1HH',
  );
}
